import type { Content } from "./types"

export const mockContents: Content[] = [
  {
    id: "1",
    title: "Sakura Dreams",
    creator: "Yuki Tanaka",
    price: 49.99,
    description: "Beautiful anime artwork featuring cherry blossoms and serene atmosphere.",
    thumbnail: "/anime1_marked.png",
    width: 1024,
    height: 1400,
  },
  {
    id: "2",
    title: "Neon Nights",
    creator: "Hiro Nakamura",
    price: 29.99,
    description: "Cyberpunk-inspired anime illustration with vibrant neon colors.",
    thumbnail: "/anime2_blur.png",
    width: 1024,
    height: 1800,
  },
  {
    id: "3",
    title: "Ocean Melody",
    creator: "Aiko Suzuki",
    price: 79.99,
    description: "Enchanting underwater scene with mystical marine elements.",
    thumbnail: "/anime3_blur.png",
    width: 1024,
    height: 1200,
  },
  {
    id: "4",
    title: "Starlight Warrior",
    creator: "Kenji Yamamoto",
    price: 39.99,
    description: "Epic fantasy character design with celestial themes.",
    thumbnail: "/anime4_marked.png",
    width: 1024,
    height: 1600,
  },
  {
    id: "5",
    title: "Autumn Whispers",
    creator: "Sakura Matsumoto",
    price: 54.99,
    description: "Warm autumn scene with falling leaves and nostalgic mood.",
    thumbnail: "/anime5_marked.png",
    width: 1024,
    height: 1350,
  },
  {
    id: "6",
    title: "Moonlit Garden",
    creator: "Ren Takahashi",
    price: 44.99,
    description: "Peaceful night garden illuminated by soft moonlight.",
    thumbnail: "/anime6_marked.png",
    width: 1024,
    height: 1500,
  },
  {
    id: "7",
    title: "Dragon's Dawn",
    creator: "Kaito Kobayashi",
    price: 89.99,
    description: "Majestic dragon artwork with sunrise background.",
    thumbnail: "/anime7_marked.png",
    width: 1024,
    height: 1700,
  },
  {
    id: "8",
    title: "Winter Solstice",
    creator: "Yumi Watanabe",
    price: 59.99,
    description: "Snowy landscape with magical winter atmosphere.",
    thumbnail: "/anime8_blur.png",
    width: 1024,
    height: 1300,
  },
  {
    id: "9",
    title: "Phoenix Rising",
    creator: "Daichi Sato",
    price: 99.99,
    description: "Powerful phoenix illustration with flames and rebirth symbolism.",
    thumbnail: "/anime9_marked.png",
    width: 1024,
    height: 1900,
  },
  {
    id: "10",
    title: "Celestial Dance",
    creator: "Mei Fujiwara",
    price: 64.99,
    description: "Ethereal character dancing among stars and cosmic elements.",
    thumbnail: "/anime10_blur.png",
    width: 1024,
    height: 1250,
  }
]
