import type { Content } from "./types"

export const mockContents: Content[] = [
  {
    id: "1",
    title: "Sakura Dreams",
    creator: "@yukitanaka",
    price: 15,
    description: "Beautiful anime artwork featuring cherry blossoms and serene atmosphere.",
    thumbnail: "/anime1_marked.png",
    width: 1024,
    height: 1400,
  },
  {
    id: "2",
    title: "Neon Nights",
    creator: "@hironaka",
    price: 10,
    description: "Cyberpunk-inspired anime illustration with vibrant neon colors.",
    thumbnail: "/anime2_blur.png",
    width: 1024,
    height: 1800,
  },
  {
    id: "3",
    title: "Ocean Melody",
    creator: "@aikosuzuki",
    price: 25,
    description: "Enchanting underwater scene with mystical marine elements.",
    thumbnail: "/anime3_blur.png",
    width: 1024,
    height: 1200,
  },
  {
    id: "4",
    title: "Starlight Warrior",
    creator: "@kenjiyama",
    price: 12,
    description: "Epic fantasy character design with celestial themes.",
    thumbnail: "/anime4_marked.png",
    width: 1024,
    height: 1600,
  },
  {
    id: "5",
    title: "Autumn Whispers",
    creator: "@sakuramtmt",
    price: 18,
    description: "Warm autumn scene with falling leaves and nostalgic mood.",
    thumbnail: "/anime5_marked.png",
    width: 1024,
    height: 1350,
  },
  {
    id: "6",
    title: "Moonlit Garden",
    creator: "@rentaka",
    price: 14,
    description: "Peaceful night garden illuminated by soft moonlight.",
    thumbnail: "/anime6_marked.png",
    width: 1024,
    height: 1500,
  },
  {
    id: "7",
    title: "Dragon's Dawn",
    creator: "@kaitokoba",
    price: 30,
    description: "Majestic dragon artwork with sunrise background.",
    thumbnail: "/anime7_marked.png",
    width: 1024,
    height: 1700,
  },
  {
    id: "8",
    title: "Winter Solstice",
    creator: "@yumiwata",
    price: 20,
    description: "Snowy landscape with magical winter atmosphere.",
    thumbnail: "/anime8_blur.png",
    width: 1024,
    height: 1300,
  },
  {
    id: "9",
    title: "Phoenix Rising",
    creator: "@daichisato",
    price: 35,
    description: "Powerful phoenix illustration with flames and rebirth symbolism.",
    thumbnail: "/anime9_marked.png",
    width: 1024,
    height: 1900,
  },
  {
    id: "10",
    title: "Celestial Dance",
    creator: "@meifuji",
    price: 22,
    description: "Ethereal character dancing among stars and cosmic elements.",
    thumbnail: "/anime10_blur.png",
    width: 1024,
    height: 1250,
  },
  {
    id: "11",
    title: "Mystic Forest",
    creator: "@takeshiishi",
    price: 16,
    description: "Enchanted forest scene with magical creatures and glowing flora.",
    thumbnail: "/anime11_blur.png",
    width: 1024,
    height: 1450,
  },
  {
    id: "12",
    title: "Crimson Sunset",
    creator: "@harukakimura",
    price: 28,
    description: "Dramatic sunset landscape with silhouetted character and warm tones.",
    thumbnail: "/anime12_blur.png",
    width: 1024,
    height: 1550,
  },
  {
    id: "13",
    title: "Ethereal Dreams",
    creator: "@laia_yuren",
    price: 19,
    description: "Dreamlike composition with floating elements and soft pastel colors.",
    thumbnail: "/anime13_blur.png",
    width: 1024,
    height: 1400,
  },
  {
    id: "14",
    title: "Cosmic Voyage",
    creator: "@laia_yuren",
    price: 22,
    description: "Interstellar journey through vibrant nebulas and distant galaxies.",
    thumbnail: "/anime14_marked.jpg",
    width: 1024,
    height: 1450,
  },
  {
    id: "15",
    title: "Shadow Guardian",
    creator: "@laia_yuren",
    price: 26,
    description: "Mysterious guardian character with dramatic lighting and powerful presence.",
    thumbnail: "/anime15_marked.png",
    width: 1024,
    height: 1650,
  },
  {
    id: "16",
    title: "Twilight Harmony",
    creator: "@laia_yuren",
    price: 24,
    description: "Serene twilight scene blending day and night with harmonious colors.",
    thumbnail: "/anime16_marked.png",
    width: 1024,
    height: 1500,
  }
]
