export const CONTRACT_ERRORS = {
  DEPLOY_FAILED: 'CONTRACT_DEPLOY_FAILED',
  INVOKE_FAILED: 'CONTRACT_INVOKE_FAILED',
  NOT_FOUND: 'CONTRACT_NOT_FOUND'
};

export const WALLET_ERRORS = {
  INVALID_PUBLIC_KEY: 'INVALID_PUBLIC_KEY',
  INVALID_SECRET: 'INVALID_SECRET_KEY',
  BALANCE_FETCH_FAILED: 'BALANCE_FETCH_FAILED'
};

export const HTTP_STATUS = {
  SUCCESS: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  SERVER_ERROR: 500
};